app/short/blueprint.py
from flask import Blueprint, render_template, request, flash
from sqlalchemy.orm import sessionmaker
from .forms import Shortner
from app.models import Urls, UrlStat
from app.extensions import db

short_url = Blueprint('short_url', __name__, template_folder='../templates/sh_url')
session_db = sessionmaker(db)


@short_url.route('/', methods=['GET', 'POST'])
def short():
    form = Shortner()
    if request.method == "POST":

        if form.validate_on_submit():
            url_base = request.form.get('URL')
            url_short = request.form.get('shortner_name')
            exist_url = Urls.quety.filter(sh_url=url_short)
            tag = request.form.get('tag_name', None)
            if exist_url:
                flash("Название ссылки занято, выберите новое или оставьте поле пустым для автогенерации.")
                return render_template('short.html', form=form)
            else:
                new_url = Urls(url=url_base, sh_url=url_short, tag=tag)
                session_db.add(new_url)
                session_db.commit()
                pass #TODO

            flash('Новая ссылка готова - sh.su/{}'.format(url_short))
        return render_template('short.html', form=form)

    return render_template('short.html', form=form)

users/blueprints.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from flask_login import login_user, logout_user, login_required

from .forms import RegisterForm, LoginForm
from .lib import generate_hash, check_hash
from models import Users

users = Blueprint('users', __name__, template_folder='templates')


@users.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        form = RegisterForm(request.form)
        if form.validate_on_submit():
            user = Users(
                username=form.username.data,
                email=form.email.data,
                password=generate_hash(form.password.data)
            )

            login_user(user)

            # flash('A confirmation email has been sent via email.', 'success')
            return redirect(url_for("index"))
    form = RegisterForm()
    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = Users.quert.filter_by(email=form.email.data).first()
        if user and check_hash(form.password.data, user.password):
            login_user(user)
            flash('Welcome.', 'success')
            return redirect(url_for('index'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('users/login.html', form=form)
    form = LoginForm()
    return render_template('users/login.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonym"

  <title>
    {% block header %}
    {% endblock header %}
  </title>
</head>
<body>
  <a href="{{ url_for('index') }}">Главная</a>
  <a href="{{ url_for('short_url.short') }}">Гененрировать ссылку</a>
  {% if current_user.is_authenticated %}
    <a>Здравствуй, {{ current_user.username }}</a>
    <a href="{{ url_for('users.logout') }}">Выход</a>
  {% else %}
    <a href="{{ url_for('users.login') }}">Вход</a>
    <a href="{{ url_for('users.register') }}">Регистрация</a>
  {% endif %}
  {% block content %}
  {% endblock content %}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block content %}

{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}

{% block header %}
  регистрация
{% endblock header %}

{% block content %}

  <form action="{{ url_for ('users.login') }}" method="post" class='form'>
    {{ form.csrf_token }}
    {% for field in form %}
      <p>{{ field.label }}</p>
      <p>{{ field }}</p>
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
    {% endfor %}

    <input type="hidden" name="next" value="{{ url_for ('users.login') }}">
  </form>

{% endblock content %}

app/templates/register.html
{% extends 'base.html' %}

{% block header %}
  регистрация
{% endblock header %}

{% block content %}

  <form action="{{ url_for ('users.register') }}" method="post" class='form'>
    {{ form.csrf_token }}
    {% for field in form %}
      <p>{{ field.label }}</p>
      <p>{{ field }}</p>
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
    {% endfor %}

    <input type="hidden" name="next" value="{{ url_for ('users.register') }}">
  </form>

{% endblock content %}